# -*- coding: utf-8 -*-
"""Actividad1_FiltradoImagen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuPN7lf2CpWIspoD8VgBX9EamTDueQQ5
"""
import cv2
import pytesseract
import numpy as np
from google.colab.patches import cv2_imshow

image_path = 'placa_4.jpg'
image = cv2.imread(image_path)

# Convertir a escala de grises
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Blurr gausiano
blurred = cv2.GaussianBlur(gray, (11,11), 0)
# Detectar bordes con Canny
edges = cv2.Canny(blurred, 100, 200)

# Mostrar imágenes procesadas
print("Imagen en escala de grises:")
cv2_imshow(gray)

print("Después de aplicar desenfoque Gaussiano:")
cv2_imshow(blurred)

print("Bordes detectados con Canny:")
cv2_imshow(edges)

# Aplicar OCR sobre la imagen desenfocada
text = pytesseract.image_to_string(blurred, config='--psm 8')

# Mostrar texto detectado
print("Texto detectado:")
print(text.strip())